# Generated by Django 3.2.3 on 2021-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='admin1@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
